### ISSUE TITLE
Add custom components to each image slide

### ISSUE THREAD

**Issue by svenadlung** [Michaelvilleneuve/react-native-photo-gallery#1]
Hi Michael, 

first of all thank you for this awesome library. Really slick, good looking solution! 
I was wondering if there is a way to add some custom views to each slide. In my case I wanna show some tags, related to the image. Any idea how I could achieve this?

Best wishes, Sven.

**Comment by Michaelvilleneuve** [comment]
Hi Sven! 

I kept this component very simple on purpose, but this would be very easily achievable. 
I'll see if I have time tomorrow, in any cases take a look at the code, there is not much of it for now. and submit a PR if you want :).

**Comment by svenadlung** [comment]
Hi @Michaelvilleneuve, that would be great. Thank you so much!

**Comment by Michaelvilleneuve** [comment]
Hi, you can now add an overlay component to each data object in c16fce1ad21109eda9064e661e89e0e2a0e2591e, it will be rendered above the image.
Remember not to make it to large or you won't be able to zoom in anymore as it is an overlay.

Try this to see how it renders : 
```javascript
{ id: '1', image: 'xxx', overlay: <View style={{ position: 'absolute', top: 40, width: 100, height: 100, backgroudColor: 'blue' }} /> }
```

**Comment by svenadlung** [comment]
Hi Michael, thank you so much. Working perfectly fine!
