### ISSUE TITLE
After recent update 0.1.5 i get a syntax error from this module

### ISSUE THREAD

**Issue by meetajhu** [Michaelvilleneuve/react-native-photo-gallery#10]
SyntaxError node_modules/react-native-photo-gallery/src/index.js: Unexpected token, expected { (3:7)

Unexpected token, expected { (3:7)"
  1 | export * from './Pagination';
  2 | export * from './Slide';
> 3 | export GalleryList from './GalleryList';

**Comment by Stmol** [comment]
+1

**Comment by Michaelvilleneuve** [comment]
Sorry for delay, please use version 0.1.6
