### ISSUE TITLE
Load dynamic images

### ISSUE THREAD

**Issue by svenadlung** [Michaelvilleneuve/react-native-photo-gallery#2]
Is there a way to load dynamic images? require() needs static images from the assets. In my case I do have an array of file paths pointing to images that just got created by react-native-camera. Any way to do it with `uri: ...` f.e.?

Regards!

**Comment by Michaelvilleneuve** [comment]
Yes sure, you can provide the same data provided to `<Image source={} />`.
Meaning you can do this `<Gallery data={{ id: 'image-1', image: { uri: 'your file path or url' }} />`

**Comment by svenadlung** [comment]
Oh, I was blind. Of course :)
Thank you so much!
