### ISSUE TITLE
Header bar covered by photo

### ISSUE THREAD

**Issue by wolfg1969** [Michaelvilleneuve/react-native-photo-gallery#3]
![screen shot 2017-08-17 at 17 00 43](https://user-images.githubusercontent.com/1585718/29404591-ef2b937c-836d-11e7-9822-0c7d5a8317ca.png)
I'm using NativeBase. The view is something like 
```
<Container>
  <Header>
    <Left>
        <Button transparent>
          <Icon name='arrow-back' />
        </Button>
      </Left>
      <Body>
        <Title>Header</Title>
      </Body>
    <Right />
  </Header>
  // <Content>
      <Gallery backgroundColor="transparent" data={data} />
  // </Content>
</Container>
```

If put <Gallery /> in <Content> block, the header is shown, but the gallery paginator is pushed to below the bottom of view.
![screen shot 2017-08-17 at 17 09 10](https://user-images.githubusercontent.com/1585718/29404883-d8c12ea2-836e-11e7-8b76-8e4055809e68.png)

**Comment by Michaelvilleneuve** [comment]
I'm not using native base, but could you please try something like that : 
```javascript
<View style={{ flex: 1 }}>
  <Header style={{ position: 'absolute', top: 0 }}>
    <Left>
        <Button transparent>
          <Icon name='arrow-back' />
        </Button>
      </Left>
      <Body>
        <Title>Header</Title>
      </Body>
    <Right />
  </Header>
  <Gallery backgroundColor="transparent" data={data} />
</View>
```

The Gallery component need to be more or less alone in the whole view, which is why using absolute for header might work.

Tell me if that works (specify the width and height of the header if needed)
